[package]
name = "read-write"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "^0.41.3", features = ["json"] }
serde = "1.0.204"
serde_json = "1.0.120"
bytes = "1.6.1"
flate2 = "1.0.30"